export { UserTypes, ViewTypes } from "./enums";
export type { UserTypeKeys, UserTypeValues } from "./enums";
export { Navigations } from "./commons";
export {
  getRoute,
  getBreadcrumb,
  matchPathPattern,
  DASHBOARD_KEY,
  DEFAULT_KEY,
  FORGOT_PASSWORD_KEY,
  HOME_KEY,
  RESET_PASSWORD_KEY,
  SIGN_IN_KEY,
  SIGN_UP_KEY,
  VERIFY_KEY,
  FIND_JOBS_KEY,
  FIND_EMPLOYERS_KEY,
  COMPANY_KEY,
  CREATE_COMPANY_KEY,
  DASHBOARD_OVERVIEW_KEY,
  DASHBOARD_APPLIED_JOBS_KEY,
  DASHBOARD_FAVORITE_JOBS_KEY,
  DASHBOARD_JOB_ALERT_KEY,
  DASHBOARD_SETTINGS_KEY,
  DASHBOARD_EMPLOYERS_PROFILE_KEY,
  DASHBOARD_POST_A_JOB_KEY,
  DASHBOARD_MY_JOBS_KEY,
  DASHBOARD_SAVED_CANDIDATE_KEY,
  DASHBOARD_PLANS_AND_BILLING_KEY,
  DASHBOARD_CATEGORIES_KEY,
} from "./routes";
export type { RouteItem } from "./routes";
export const DEFAULT_PADDING_X = "200px";
